### ISSUE TITLE
Unable to copy output CSS

### ISSUE THREAD

**Issue by le717** [RyanZim/postcss-repl#137]
I am unable to copy the output CSS. Performing Ctrl+A with the editor focused selects all on the input. Manually selecting all the lines then hitting Ctrl+C or right-click>Copy copies whatever is selected in the input editor.

Running Fx Dev Edition 63.0b13 (64-bit) on Win10 1809.

Thank you for your time! Let me know if you need more info! You have a very helpful site here. :)

**Comment by RyanZim** [comment]
Good catch, same problem here. Funny that I never tested this. We should fix the selection bug, and potentially add a copy `all button`
