### ISSUE TITLE
Add postcss-preset-env

### ISSUE THREAD

**Issue by RyanZim** [RyanZim/postcss-repl#15]
https://github.com/jonathantneal/postcss-preset-env

**Comment by sylvainpolletvillard** [comment]
Should we think about how to configure plugins from the REPL itself ? This would be useful for this plugin in particular. I put the config property in the generated plugins.json file with this in mind.

**Comment by RyanZim** [comment]
@sylvainpolletvillard We need that eventually. However, it doesn't fit with the current design very well. I'd like to get the plugin config moved to a collapsing sidebar; that will make this easier.

One of the first things I'd like to wire up option-wise is `browsers`. A lot of plugins support it; we should have one textarea that sets the browserlist config for all plugins.
