### ISSUE TITLE
Move all CSS to svelte components

### ISSUE THREAD

**Issue by RyanZim** [RyanZim/postcss-repl#43]
Refs https://github.com/RyanZim/postcss-repl/pull/41#issuecomment-376181687.

I'll do this after #42 gets merged. @sylvainpolletvillard you're aware that svelte scopes styles, correct?

**Comment by sylvainpolletvillard** [comment]
I don't know much about Svelte, but scopes styles would be great

**Comment by sylvainpolletvillard** [comment]
I gave it a try and it seems to work well: https://github.com/RyanZim/postcss-repl/pull/46
